import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const now = new Date().toISOString();
    const dealEndsAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();

    const sampleProducts = [
        // Women's Clothing (15 products)
        {
            name: "Elegant Silk Maxi Dress",
            slug: "elegant-silk-maxi-dress",
            brandId: 5,
            categoryId: 1,
            price: 249.99,
            originalPrice: null,
            description: "Luxurious silk maxi dress with flowing silhouette. Perfect for special occasions with its sophisticated draping and comfortable fit.",
            image: "/images/products/product-1.jpg",
            images: ["/images/products/product-1-1.jpg", "/images/products/product-1-2.jpg", "/images/products/product-1-3.jpg", "/images/products/product-1-4.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Navy", "Burgundy", "Emerald", "Ivory"],
            rating: 4.8,
            reviews: 342,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "ethical",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Classic White Button-Up Shirt",
            slug: "classic-white-button-up-shirt",
            brandId: 21,
            categoryId: 1,
            price: 59.99,
            originalPrice: 89.99,
            description: "Timeless white button-up crafted from premium cotton. Features a modern fit and versatile style for work or casual wear.",
            image: "/images/products/product-2.jpg",
            images: ["/images/products/product-2-1.jpg", "/images/products/product-2-2.jpg", "/images/products/product-2-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["White", "Cream", "Light Blue"],
            rating: 4.6,
            reviews: 287,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 33,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "High-Waisted Wide Leg Trousers",
            slug: "high-waisted-wide-leg-trousers",
            brandId: 22,
            categoryId: 1,
            price: 89.99,
            originalPrice: null,
            description: "Contemporary wide-leg trousers with high-waist design. Crafted from premium fabric blend for comfort and style all day long.",
            image: "/images/products/product-3.jpg",
            images: ["/images/products/product-3-1.jpg", "/images/products/product-3-2.jpg", "/images/products/product-3-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Navy", "Camel", "Gray"],
            rating: 4.7,
            reviews: 198,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Oversized Denim Jacket",
            slug: "oversized-denim-jacket",
            brandId: 7,
            categoryId: 1,
            price: 79.99,
            originalPrice: null,
            description: "Relaxed fit denim jacket with vintage wash. Features classic button closure and multiple pockets for everyday style.",
            image: "/images/products/product-4.jpg",
            images: ["/images/products/product-4-1.jpg", "/images/products/product-4-2.jpg", "/images/products/product-4-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Light Blue", "Dark Blue", "Black", "White"],
            rating: 4.9,
            reviews: 456,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "eco",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Floral Summer Wrap Dress",
            slug: "floral-summer-wrap-dress",
            brandId: 3,
            categoryId: 1,
            price: 49.99,
            originalPrice: 79.99,
            description: "Feminine wrap dress with vibrant floral print. Lightweight fabric and adjustable tie waist make it perfect for warm weather.",
            image: "/images/products/product-5.jpg",
            images: ["/images/products/product-5-1.jpg", "/images/products/product-5-2.jpg", "/images/products/product-5-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Pink Floral", "Blue Floral", "Yellow Floral"],
            rating: 4.5,
            reviews: 234,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 38,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Cashmere V-Neck Sweater",
            slug: "cashmere-v-neck-sweater",
            brandId: 6,
            categoryId: 1,
            price: 189.99,
            originalPrice: null,
            description: "Luxurious 100% cashmere sweater with classic V-neck. Ultra-soft and warm, perfect for layering or wearing alone.",
            image: "/images/products/product-6.jpg",
            images: ["/images/products/product-6-1.jpg", "/images/products/product-6-2.jpg", "/images/products/product-6-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Camel", "Gray", "Navy", "Cream"],
            rating: 4.9,
            reviews: 167,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Pleated Midi Skirt",
            slug: "pleated-midi-skirt",
            brandId: 23,
            categoryId: 1,
            price: 69.99,
            originalPrice: null,
            description: "Elegant pleated skirt with midi length. Flowing design and elastic waistband provide comfort and sophistication.",
            image: "/images/products/product-7.jpg",
            images: ["/images/products/product-7-1.jpg", "/images/products/product-7-2.jpg", "/images/products/product-7-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Navy", "Burgundy", "Forest Green"],
            rating: 4.6,
            reviews: 289,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "local",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Leather Biker Jacket",
            slug: "leather-biker-jacket",
            brandId: 11,
            categoryId: 1,
            price: 299.99,
            originalPrice: null,
            description: "Genuine leather jacket with edgy biker design. Features asymmetric zip, metal hardware, and quilted shoulders for attitude.",
            image: "/images/products/product-8.jpg",
            images: ["/images/products/product-8-1.jpg", "/images/products/product-8-2.jpg", "/images/products/product-8-3.jpg", "/images/products/product-8-4.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Brown", "Burgundy"],
            rating: 4.8,
            reviews: 412,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Striped Breton Top",
            slug: "striped-breton-top",
            brandId: 18,
            categoryId: 1,
            price: 39.99,
            originalPrice: 59.99,
            description: "Classic Breton striped top in soft cotton. Timeless design with three-quarter sleeves perfect for casual everyday wear.",
            image: "/images/products/product-9.jpg",
            images: ["/images/products/product-9-1.jpg", "/images/products/product-9-2.jpg", "/images/products/product-9-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Navy/White", "Black/White", "Red/White"],
            rating: 4.7,
            reviews: 356,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 33,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Tailored Blazer",
            slug: "tailored-blazer",
            brandId: 21,
            categoryId: 1,
            price: 149.99,
            originalPrice: null,
            description: "Sharp tailored blazer with structured shoulders. Professional yet versatile piece that transitions from office to evening.",
            image: "/images/products/product-10.jpg",
            images: ["/images/products/product-10-1.jpg", "/images/products/product-10-2.jpg", "/images/products/product-10-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Navy", "Gray", "Camel"],
            rating: 4.8,
            reviews: 298,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Ribbed Knit Turtleneck",
            slug: "ribbed-knit-turtleneck",
            brandId: 9,
            categoryId: 1,
            price: 44.99,
            originalPrice: null,
            description: "Cozy ribbed turtleneck in soft knit fabric. Form-fitting design perfect for layering under jackets or wearing alone.",
            image: "/images/products/product-11.jpg",
            images: ["/images/products/product-11-1.jpg", "/images/products/product-11-2.jpg", "/images/products/product-11-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "White", "Camel", "Gray", "Burgundy"],
            rating: 4.5,
            reviews: 187,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "eco",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Wide Leg Cropped Jeans",
            slug: "wide-leg-cropped-jeans",
            brandId: 7,
            categoryId: 1,
            price: 89.99,
            originalPrice: 119.99,
            description: "Modern wide-leg jeans with cropped length. Premium denim with comfortable stretch and flattering high-rise fit.",
            image: "/images/products/product-12.jpg",
            images: ["/images/products/product-12-1.jpg", "/images/products/product-12-2.jpg", "/images/products/product-12-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Light Blue", "Dark Blue", "Black", "White"],
            rating: 4.6,
            reviews: 423,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 25,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Satin Slip Dress",
            slug: "satin-slip-dress",
            brandId: 3,
            categoryId: 1,
            price: 79.99,
            originalPrice: null,
            description: "Luxe satin slip dress with adjustable straps. Effortlessly elegant design perfect for evening events or date nights.",
            image: "/images/products/product-13.jpg",
            images: ["/images/products/product-13-1.jpg", "/images/products/product-13-2.jpg", "/images/products/product-13-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Champagne", "Emerald", "Ruby"],
            rating: 4.7,
            reviews: 267,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Puff Sleeve Blouse",
            slug: "puff-sleeve-blouse",
            brandId: 19,
            categoryId: 1,
            price: 49.99,
            originalPrice: null,
            description: "Romantic blouse with statement puff sleeves. Lightweight fabric and feminine silhouette create an effortlessly chic look.",
            image: "/images/products/product-14.jpg",
            images: ["/images/products/product-14-1.jpg", "/images/products/product-14-2.jpg", "/images/products/product-14-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["White", "Black", "Pink", "Blue"],
            rating: 4.4,
            reviews: 156,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "local",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Wool Blend Coat",
            slug: "wool-blend-coat",
            brandId: 21,
            categoryId: 1,
            price: 229.99,
            originalPrice: null,
            description: "Premium wool blend coat with timeless design. Features classic lapels, button closure, and warm lining for cold weather.",
            image: "/images/products/product-15.jpg",
            images: ["/images/products/product-15-1.jpg", "/images/products/product-15-2.jpg", "/images/products/product-15-3.jpg", "/images/products/product-15-4.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Camel", "Black", "Navy", "Gray"],
            rating: 4.9,
            reviews: 389,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        // Men's Clothing (12 products)
        {
            name: "Oxford Button-Down Shirt",
            slug: "oxford-button-down-shirt",
            brandId: 8,
            categoryId: 2,
            price: 54.99,
            originalPrice: null,
            description: "Classic Oxford shirt in premium cotton. Features button-down collar and versatile style perfect for work or casual occasions.",
            image: "/images/products/product-16.jpg",
            images: ["/images/products/product-16-1.jpg", "/images/products/product-16-2.jpg", "/images/products/product-16-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["White", "Light Blue", "Pink", "Navy"],
            rating: 4.6,
            reviews: 312,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Slim Fit Chinos",
            slug: "slim-fit-chinos",
            brandId: 8,
            categoryId: 2,
            price: 69.99,
            originalPrice: 99.99,
            description: "Tailored chinos with modern slim fit. Comfortable stretch fabric and versatile style suitable for any occasion.",
            image: "/images/products/product-17.jpg",
            images: ["/images/products/product-17-1.jpg", "/images/products/product-17-2.jpg", "/images/products/product-17-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Khaki", "Navy", "Black", "Gray", "Olive"],
            rating: 4.7,
            reviews: 445,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 30,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Leather Bomber Jacket",
            slug: "leather-bomber-jacket",
            brandId: 5,
            categoryId: 2,
            price: 399.99,
            originalPrice: null,
            description: "Premium leather bomber with ribbed cuffs. Classic design crafted from genuine leather for timeless style and durability.",
            image: "/images/products/product-18.jpg",
            images: ["/images/products/product-18-1.jpg", "/images/products/product-18-2.jpg", "/images/products/product-18-3.jpg", "/images/products/product-18-4.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Brown", "Navy"],
            rating: 4.9,
            reviews: 278,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Merino Wool Sweater",
            slug: "merino-wool-sweater",
            brandId: 9,
            categoryId: 2,
            price: 89.99,
            originalPrice: null,
            description: "Luxurious merino wool crew neck sweater. Temperature-regulating fabric provides comfort in any weather while maintaining shape.",
            image: "/images/products/product-19.jpg",
            images: ["/images/products/product-19-1.jpg", "/images/products/product-19-2.jpg", "/images/products/product-19-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Navy", "Gray", "Black", "Burgundy", "Camel"],
            rating: 4.8,
            reviews: 367,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "eco",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Tailored Suit Jacket",
            slug: "tailored-suit-jacket",
            brandId: 21,
            categoryId: 2,
            price: 279.99,
            originalPrice: null,
            description: "Sharp tailored suit jacket with modern fit. Premium wool blend fabric and expert construction for professional confidence.",
            image: "/images/products/product-20.jpg",
            images: ["/images/products/product-20-1.jpg", "/images/products/product-20-2.jpg", "/images/products/product-20-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Charcoal", "Navy", "Black"],
            rating: 4.8,
            reviews: 234,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Raw Denim Jeans",
            slug: "raw-denim-jeans",
            brandId: 7,
            categoryId: 2,
            price: 129.99,
            originalPrice: 179.99,
            description: "Premium raw denim jeans that age beautifully. Classic straight fit with selvedge detail for authentic style.",
            image: "/images/products/product-21.jpg",
            images: ["/images/products/product-21-1.jpg", "/images/products/product-21-2.jpg", "/images/products/product-21-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Raw Indigo", "Black", "Dark Blue"],
            rating: 4.7,
            reviews: 498,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 28,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Quilted Vest",
            slug: "quilted-vest",
            brandId: 8,
            categoryId: 2,
            price: 84.99,
            originalPrice: null,
            description: "Versatile quilted vest for layering. Lightweight insulation and zip pockets make it perfect for transitional weather.",
            image: "/images/products/product-22.jpg",
            images: ["/images/products/product-22-1.jpg", "/images/products/product-22-2.jpg", "/images/products/product-22-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Navy", "Black", "Olive", "Gray"],
            rating: 4.5,
            reviews: 289,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "eco",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Performance Polo Shirt",
            slug: "performance-polo-shirt",
            brandId: 1,
            categoryId: 2,
            price: 59.99,
            originalPrice: null,
            description: "Technical polo with moisture-wicking fabric. Classic style meets athletic performance for active lifestyle.",
            image: "/images/products/product-23.jpg",
            images: ["/images/products/product-23-1.jpg", "/images/products/product-23-2.jpg", "/images/products/product-23-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["White", "Navy", "Black", "Red", "Gray"],
            rating: 4.6,
            reviews: 376,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Striped Dress Shirt",
            slug: "striped-dress-shirt",
            brandId: 21,
            categoryId: 2,
            price: 79.99,
            originalPrice: null,
            description: "Refined dress shirt with subtle stripes. Egyptian cotton fabric and tailored fit perfect for professional settings.",
            image: "/images/products/product-24.jpg",
            images: ["/images/products/product-24-1.jpg", "/images/products/product-24-2.jpg", "/images/products/product-24-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Blue Stripe", "Pink Stripe", "Gray Stripe"],
            rating: 4.7,
            reviews: 223,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Hooded Parka",
            slug: "hooded-parka",
            brandId: 2,
            categoryId: 2,
            price: 199.99,
            originalPrice: null,
            description: "Insulated parka with detachable hood. Water-resistant shell and warm lining provide ultimate cold-weather protection.",
            image: "/images/products/product-25.jpg",
            images: ["/images/products/product-25-1.jpg", "/images/products/product-25-2.jpg", "/images/products/product-25-3.jpg", "/images/products/product-25-4.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Navy", "Black", "Olive", "Gray"],
            rating: 4.8,
            reviews: 412,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Cotton Henley Shirt",
            slug: "cotton-henley-shirt",
            brandId: 8,
            categoryId: 2,
            price: 39.99,
            originalPrice: 59.99,
            description: "Casual henley in soft cotton blend. Three-button placket and relaxed fit perfect for weekend wear.",
            image: "/images/products/product-26.jpg",
            images: ["/images/products/product-26-1.jpg", "/images/products/product-26-2.jpg", "/images/products/product-26-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["White", "Navy", "Gray", "Black", "Burgundy"],
            rating: 4.5,
            reviews: 267,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 33,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Wool Dress Pants",
            slug: "wool-dress-pants",
            brandId: 21,
            categoryId: 2,
            price: 149.99,
            originalPrice: null,
            description: "Refined dress pants in premium wool. Impeccable tailoring and classic fit perfect for formal occasions.",
            image: "/images/products/product-27.jpg",
            images: ["/images/products/product-27-1.jpg", "/images/products/product-27-2.jpg", "/images/products/product-27-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Charcoal", "Navy", "Black", "Gray"],
            rating: 4.8,
            reviews: 198,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "ethical",
            createdAt: now,
            updatedAt: now,
        },
        // Kids Clothing (8 products)
        {
            name: "Rainbow Stripe T-Shirt",
            slug: "rainbow-stripe-t-shirt",
            brandId: 8,
            categoryId: 3,
            price: 19.99,
            originalPrice: null,
            description: "Fun rainbow striped tee in soft cotton. Bright colors and comfortable fit perfect for active kids.",
            image: "/images/products/product-28.jpg",
            images: ["/images/products/product-28-1.jpg", "/images/products/product-28-2.jpg", "/images/products/product-28-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Rainbow", "Blue Stripe", "Pink Stripe"],
            rating: 4.7,
            reviews: 234,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "eco",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Denim Overalls",
            slug: "denim-overalls",
            brandId: 8,
            categoryId: 3,
            price: 44.99,
            originalPrice: 64.99,
            description: "Classic denim overalls with adjustable straps. Durable construction and multiple pockets for everyday adventures.",
            image: "/images/products/product-29.jpg",
            images: ["/images/products/product-29-1.jpg", "/images/products/product-29-2.jpg", "/images/products/product-29-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Light Blue", "Dark Blue", "Black"],
            rating: 4.8,
            reviews: 378,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 31,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Fleece Hoodie",
            slug: "fleece-hoodie",
            brandId: 8,
            categoryId: 3,
            price: 34.99,
            originalPrice: null,
            description: "Cozy fleece hoodie for chilly days. Soft interior and front pocket keep kids warm and comfortable.",
            image: "/images/products/product-30.jpg",
            images: ["/images/products/product-30-1.jpg", "/images/products/product-30-2.jpg", "/images/products/product-30-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Navy", "Gray", "Pink", "Black", "Red"],
            rating: 4.6,
            reviews: 456,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Graphic Print Sweatshirt",
            slug: "graphic-print-sweatshirt",
            brandId: 4,
            categoryId: 3,
            price: 29.99,
            originalPrice: null,
            description: "Fun sweatshirt with bold graphic print. Cotton-blend fabric provides comfort for all-day play.",
            image: "/images/products/product-31.jpg",
            images: ["/images/products/product-31-1.jpg", "/images/products/product-31-2.jpg", "/images/products/product-31-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Navy", "Gray", "White", "Black"],
            rating: 4.5,
            reviews: 289,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Cotton Cargo Pants",
            slug: "cotton-cargo-pants",
            brandId: 8,
            categoryId: 3,
            price: 39.99,
            originalPrice: null,
            description: "Durable cargo pants with multiple pockets. Comfortable cotton fabric and adjustable waist for growing kids.",
            image: "/images/products/product-32.jpg",
            images: ["/images/products/product-32-1.jpg", "/images/products/product-32-2.jpg", "/images/products/product-32-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Khaki", "Navy", "Black", "Olive"],
            rating: 4.7,
            reviews: 345,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Puffer Jacket",
            slug: "puffer-jacket",
            brandId: 9,
            categoryId: 3,
            price: 64.99,
            originalPrice: 89.99,
            description: "Warm puffer jacket with lightweight insulation. Water-resistant shell and hood provide protection from elements.",
            image: "/images/products/product-33.jpg",
            images: ["/images/products/product-33-1.jpg", "/images/products/product-33-2.jpg", "/images/products/product-33-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Navy", "Pink", "Black", "Red"],
            rating: 4.8,
            reviews: 412,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 28,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Printed Leggings",
            slug: "printed-leggings",
            brandId: 4,
            categoryId: 3,
            price: 24.99,
            originalPrice: null,
            description: "Stretchy leggings with fun prints. Soft fabric blend moves with active kids for maximum comfort.",
            image: "/images/products/product-34.jpg",
            images: ["/images/products/product-34-1.jpg", "/images/products/product-34-2.jpg", "/images/products/product-34-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Floral", "Dots", "Stars", "Stripe"],
            rating: 4.6,
            reviews: 267,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "eco",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Knit Cardigan",
            slug: "knit-cardigan",
            brandId: 9,
            categoryId: 3,
            price: 49.99,
            originalPrice: null,
            description: "Cozy knit cardigan with button front. Soft yarn and classic style perfect for layering.",
            image: "/images/products/product-35.jpg",
            images: ["/images/products/product-35-1.jpg", "/images/products/product-35-2.jpg", "/images/products/product-35-3.jpg"],
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Navy", "Gray", "Cream", "Pink"],
            rating: 4.7,
            reviews: 178,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        // Shoes (10 products)
        {
            name: "Classic Leather Sneakers",
            slug: "classic-leather-sneakers",
            brandId: 1,
            categoryId: 4,
            price: 89.99,
            originalPrice: null,
            description: "Timeless leather sneakers with cushioned sole. Versatile white design pairs perfectly with any casual outfit.",
            image: "/images/products/product-36.jpg",
            images: ["/images/products/product-36-1.jpg", "/images/products/product-36-2.jpg", "/images/products/product-36-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["White", "Black", "Navy"],
            rating: 4.8,
            reviews: 534,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Running Shoes",
            slug: "running-shoes",
            brandId: 2,
            categoryId: 4,
            price: 129.99,
            originalPrice: 179.99,
            description: "High-performance running shoes with responsive cushioning. Breathable mesh upper and supportive sole for long distances.",
            image: "/images/products/product-37.jpg",
            images: ["/images/products/product-37-1.jpg", "/images/products/product-37-2.jpg", "/images/products/product-37-3.jpg", "/images/products/product-37-4.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["Black/White", "Gray/Blue", "Navy/Orange"],
            rating: 4.9,
            reviews: 678,
            inStock: true,
            featured: true,
            deal: true,
            dealDiscount: 28,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Chelsea Boots",
            slug: "chelsea-boots",
            brandId: 5,
            categoryId: 4,
            price: 249.99,
            originalPrice: null,
            description: "Elegant Chelsea boots in premium leather. Classic elastic side panels and sleek design perfect for any occasion.",
            image: "/images/products/product-38.jpg",
            images: ["/images/products/product-38-1.jpg", "/images/products/product-38-2.jpg", "/images/products/product-38-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["Black", "Brown", "Burgundy"],
            rating: 4.8,
            reviews: 423,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Strappy Heeled Sandals",
            slug: "strappy-heeled-sandals",
            brandId: 3,
            categoryId: 4,
            price: 79.99,
            originalPrice: null,
            description: "Elegant heeled sandals with delicate straps. Comfortable heel height and sophisticated design for evening wear.",
            image: "/images/products/product-39.jpg",
            images: ["/images/products/product-39-1.jpg", "/images/products/product-39-2.jpg", "/images/products/product-39-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["Black", "Nude", "Silver", "Gold"],
            rating: 4.6,
            reviews: 289,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Hiking Boots",
            slug: "hiking-boots",
            brandId: 2,
            categoryId: 4,
            price: 159.99,
            originalPrice: null,
            description: "Rugged hiking boots with waterproof membrane. Durable construction and excellent traction for outdoor adventures.",
            image: "/images/products/product-40.jpg",
            images: ["/images/products/product-40-1.jpg", "/images/products/product-40-2.jpg", "/images/products/product-40-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["Brown", "Black", "Gray"],
            rating: 4.9,
            reviews: 567,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: "eco",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Slip-On Loafers",
            slug: "slip-on-loafers",
            brandId: 21,
            categoryId: 4,
            price: 119.99,
            originalPrice: 169.99,
            description: "Classic leather loafers with modern comfort. Easy slip-on design and cushioned insole perfect for business casual.",
            image: "/images/products/product-41.jpg",
            images: ["/images/products/product-41-1.jpg", "/images/products/product-41-2.jpg", "/images/products/product-41-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["Black", "Brown", "Burgundy"],
            rating: 4.7,
            reviews: 345,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 30,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Platform Sneakers",
            slug: "platform-sneakers",
            brandId: 10,
            categoryId: 4,
            price: 69.99,
            originalPrice: null,
            description: "Trendy platform sneakers with chunky sole. Canvas upper and comfortable height boost perfect for casual style.",
            image: "/images/products/product-42.jpg",
            images: ["/images/products/product-42-1.jpg", "/images/products/product-42-2.jpg", "/images/products/product-42-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["White", "Black", "Pink", "Gray"],
            rating: 4.5,
            reviews: 412,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Ankle Strap Heels",
            slug: "ankle-strap-heels",
            brandId: 3,
            categoryId: 4,
            price: 99.99,
            originalPrice: null,
            description: "Sophisticated heels with secure ankle strap. Elegant silhouette and comfortable fit for special occasions.",
            image: "/images/products/product-43.jpg",
            images: ["/images/products/product-43-1.jpg", "/images/products/product-43-2.jpg", "/images/products/product-43-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["Black", "Nude", "Red", "Navy"],
            rating: 4.6,
            reviews: 278,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Athletic Training Shoes",
            slug: "athletic-training-shoes",
            brandId: 1,
            categoryId: 4,
            price: 109.99,
            originalPrice: null,
            description: "Versatile training shoes for gym and everyday wear. Supportive design and flexible sole adapt to any workout.",
            image: "/images/products/product-44.jpg",
            images: ["/images/products/product-44-1.jpg", "/images/products/product-44-2.jpg", "/images/products/product-44-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["Black", "Gray", "White", "Navy"],
            rating: 4.7,
            reviews: 489,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Leather Sandals",
            slug: "leather-sandals",
            brandId: 14,
            categoryId: 4,
            price: 59.99,
            originalPrice: 89.99,
            description: "Minimalist leather sandals with adjustable straps. Comfortable footbed and timeless design for warm weather.",
            image: "/images/products/product-45.jpg",
            images: ["/images/products/product-45-1.jpg", "/images/products/product-45-2.jpg", "/images/products/product-45-3.jpg"],
            sizes: ["6", "7", "8", "9", "10", "11"],
            colors: ["Brown", "Black", "Tan"],
            rating: 4.8,
            reviews: 356,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 33,
            dealEndsAt: dealEndsAt,
            movement: "ethical",
            createdAt: now,
            updatedAt: now,
        },
        // Bags (7 products)
        {
            name: "Leather Tote Bag",
            slug: "leather-tote-bag",
            brandId: 6,
            categoryId: 5,
            price: 299.99,
            originalPrice: null,
            description: "Luxurious leather tote with spacious interior. Classic design and premium materials perfect for work or travel.",
            image: "/images/products/product-46.jpg",
            images: ["/images/products/product-46-1.jpg", "/images/products/product-46-2.jpg", "/images/products/product-46-3.jpg", "/images/products/product-46-4.jpg"],
            sizes: ["One Size"],
            colors: ["Black", "Brown", "Tan", "Navy"],
            rating: 4.9,
            reviews: 423,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Canvas Backpack",
            slug: "canvas-backpack",
            brandId: 8,
            categoryId: 5,
            price: 69.99,
            originalPrice: 99.99,
            description: "Durable canvas backpack with laptop compartment. Multiple pockets and comfortable straps for everyday carry.",
            image: "/images/products/product-47.jpg",
            images: ["/images/products/product-47-1.jpg", "/images/products/product-47-2.jpg", "/images/products/product-47-3.jpg"],
            sizes: ["One Size"],
            colors: ["Navy", "Black", "Gray", "Olive"],
            rating: 4.7,
            reviews: 567,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 30,
            dealEndsAt: dealEndsAt,
            movement: "eco",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Crossbody Bag",
            slug: "crossbody-bag",
            brandId: 3,
            categoryId: 5,
            price: 89.99,
            originalPrice: null,
            description: "Compact crossbody bag with adjustable strap. Perfect size for essentials with secure zip closure.",
            image: "/images/products/product-48.jpg",
            images: ["/images/products/product-48-1.jpg", "/images/products/product-48-2.jpg", "/images/products/product-48-3.jpg"],
            sizes: ["One Size"],
            colors: ["Black", "Camel", "Burgundy", "Navy"],
            rating: 4.6,
            reviews: 389,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Evening Clutch",
            slug: "evening-clutch",
            brandId: 5,
            categoryId: 5,
            price: 149.99,
            originalPrice: null,
            description: "Elegant clutch bag for formal occasions. Sleek design with chain strap and luxurious finish.",
            image: "/images/products/product-49.jpg",
            images: ["/images/products/product-49-1.jpg", "/images/products/product-49-2.jpg", "/images/products/product-49-3.jpg"],
            sizes: ["One Size"],
            colors: ["Black", "Silver", "Gold", "Navy"],
            rating: 4.8,
            reviews: 234,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Travel Duffle Bag",
            slug: "travel-duffle-bag",
            brandId: 2,
            categoryId: 5,
            price: 119.99,
            originalPrice: null,
            description: "Spacious duffle bag perfect for weekend trips. Durable material with multiple compartments and comfortable handles.",
            image: "/images/products/product-50.jpg",
            images: ["/images/products/product-50-1.jpg", "/images/products/product-50-2.jpg", "/images/products/product-50-3.jpg"],
            sizes: ["One Size"],
            colors: ["Black", "Navy", "Gray"],
            rating: 4.7,
            reviews: 445,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Mini Shoulder Bag",
            slug: "mini-shoulder-bag",
            brandId: 25,
            categoryId: 5,
            price: 54.99,
            originalPrice: 79.99,
            description: "Cute mini bag with long shoulder strap. Just right for phone, wallet, and keys with trendy design.",
            image: "/images/products/product-51.jpg",
            images: ["/images/products/product-51-1.jpg", "/images/products/product-51-2.jpg", "/images/products/product-51-3.jpg"],
            sizes: ["One Size"],
            colors: ["Pink", "Black", "White", "Green"],
            rating: 4.5,
            reviews: 312,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 31,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Structured Handbag",
            slug: "structured-handbag",
            brandId: 6,
            categoryId: 5,
            price: 249.99,
            originalPrice: null,
            description: "Sophisticated structured handbag in fine leather. Professional style with organized interior compartments.",
            image: "/images/products/product-52.jpg",
            images: ["/images/products/product-52-1.jpg", "/images/products/product-52-2.jpg", "/images/products/product-52-3.jpg"],
            sizes: ["One Size"],
            colors: ["Black", "Brown", "Navy", "Red"],
            rating: 4.8,
            reviews: 378,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        // Accessories (5 products)
        {
            name: "Leather Belt",
            slug: "leather-belt",
            brandId: 7,
            categoryId: 6,
            price: 49.99,
            originalPrice: null,
            description: "Classic leather belt with metal buckle. Versatile design suitable for casual and formal wear.",
            image: "/images/products/product-53.jpg",
            images: ["/images/products/product-53-1.jpg", "/images/products/product-53-2.jpg", "/images/products/product-53-3.jpg"],
            sizes: ["One Size"],
            colors: ["Black", "Brown", "Tan"],
            rating: 4.7,
            reviews: 289,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Wide Brim Hat",
            slug: "wide-brim-hat",
            brandId: 12,
            categoryId: 6,
            price: 59.99,
            originalPrice: 84.99,
            description: "Stylish wide brim hat for sun protection. Lightweight straw construction perfect for summer days.",
            image: "/images/products/product-54.jpg",
            images: ["/images/products/product-54-1.jpg", "/images/products/product-54-2.jpg", "/images/products/product-54-3.jpg"],
            sizes: ["One Size"],
            colors: ["Natural", "Black", "Navy"],
            rating: 4.6,
            reviews: 267,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 29,
            dealEndsAt: dealEndsAt,
            movement: "ethical",
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Cashmere Scarf",
            slug: "cashmere-scarf",
            brandId: 6,
            categoryId: 6,
            price: 129.99,
            originalPrice: null,
            description: "Luxurious cashmere scarf in classic design. Incredibly soft and warm for cold weather.",
            image: "/images/products/product-55.jpg",
            images: ["/images/products/product-55-1.jpg", "/images/products/product-55-2.jpg", "/images/products/product-55-3.jpg"],
            sizes: ["One Size"],
            colors: ["Camel", "Black", "Gray", "Navy", "Burgundy"],
            rating: 4.9,
            reviews: 423,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Baseball Cap",
            slug: "baseball-cap",
            brandId: 1,
            categoryId: 6,
            price: 29.99,
            originalPrice: null,
            description: "Classic baseball cap with adjustable strap. Cotton construction and curved brim for casual style.",
            image: "/images/products/product-56.jpg",
            images: ["/images/products/product-56-1.jpg", "/images/products/product-56-2.jpg", "/images/products/product-56-3.jpg"],
            sizes: ["One Size"],
            colors: ["Black", "Navy", "White", "Gray", "Red"],
            rating: 4.5,
            reviews: 345,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Knit Beanie",
            slug: "knit-beanie",
            brandId: 9,
            categoryId: 6,
            price: 34.99,
            originalPrice: null,
            description: "Cozy knit beanie for cold weather. Soft acrylic blend and classic fold-up design.",
            image: "/images/products/product-57.jpg",
            images: ["/images/products/product-57-1.jpg", "/images/products/product-57-2.jpg", "/images/products/product-57-3.jpg"],
            sizes: ["One Size"],
            colors: ["Black", "Gray", "Navy", "Burgundy", "Cream"],
            rating: 4.6,
            reviews: 278,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        // Jewelry (3 products)
        {
            name: "Gold Chain Necklace",
            slug: "gold-chain-necklace",
            brandId: 5,
            categoryId: 7,
            price: 199.99,
            originalPrice: null,
            description: "Elegant gold-plated chain necklace. Timeless design perfect for layering or wearing alone.",
            image: "/images/products/product-58.jpg",
            images: ["/images/products/product-58-1.jpg", "/images/products/product-58-2.jpg", "/images/products/product-58-3.jpg"],
            sizes: ["One Size"],
            colors: ["Gold", "Silver", "Rose Gold"],
            rating: 4.8,
            reviews: 289,
            inStock: true,
            featured: true,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Hoop Earrings",
            slug: "hoop-earrings",
            brandId: 5,
            categoryId: 7,
            price: 79.99,
            originalPrice: 119.99,
            description: "Classic hoop earrings in various sizes. Lightweight design with secure closure for everyday wear.",
            image: "/images/products/product-59.jpg",
            images: ["/images/products/product-59-1.jpg", "/images/products/product-59-2.jpg", "/images/products/product-59-3.jpg"],
            sizes: ["One Size"],
            colors: ["Gold", "Silver", "Rose Gold"],
            rating: 4.7,
            reviews: 456,
            inStock: true,
            featured: false,
            deal: true,
            dealDiscount: 33,
            dealEndsAt: dealEndsAt,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: "Charm Bracelet",
            slug: "charm-bracelet",
            brandId: 5,
            categoryId: 7,
            price: 149.99,
            originalPrice: null,
            description: "Delicate charm bracelet with adjustable chain. Elegant design perfect for stacking or wearing solo.",
            image: "/images/products/product-60.jpg",
            images: ["/images/products/product-60-1.jpg", "/images/products/product-60-2.jpg", "/images/products/product-60-3.jpg"],
            sizes: ["One Size"],
            colors: ["Gold", "Silver", "Rose Gold"],
            rating: 4.8,
            reviews: 334,
            inStock: true,
            featured: false,
            deal: false,
            dealDiscount: null,
            dealEndsAt: null,
            movement: null,
            createdAt: now,
            updatedAt: now,
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully - 60 fashion products added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});